when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
             enabled: true
             collect: true
             only_exceptions: false

when@test:
    framework:
        profiler: { collect: false }
